env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  'react/jsx-filename-extension': 'off',
  'no-underscore-dangle': 'off',
  'jsx-a11y/img-redundant-alt': 'off',
  'react/jsx-props-no-spreading': 'off',
  'comma-dangle': 'error',
}
